# Site settings
author: Karl Dorsainvil
title: Data Science
header-img: img/home-bg.png
email: kdorsain@gmail.com
copyright_name: Karl Dorsainvil
description: > # this means to ignore newlines until "baseurl:"
  Data Science Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  KDORS14

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
